### PR TITLE
canister monitoring API

### PR DESCRIPTION
**Pull request by komal-rs**

### CODE REVIEW

**Review by ravibazz — APPROVED** [review]

**Review by saikatdas0790 — CHANGES_REQUESTED** [review]
@komal-rs 

Couple of quick questions:
- What is the trigger for the metric collection? Let's add that
- Instead of spinning up a GKE cluster, let's use the offchain agent on Fly for all of our stateless processing needs? Or a separate service on Fly that will utilize the OpenTelemetry collector?
- How does the `http_sd_config` get read by Prometheus? Is this a REST API? Is there authorization involved?
- Are we adding authorization to the /metrics endpoint? Might be a good idea for these endpoints to be public
- Does Prometheus come with a frontend of its own or do we need a separate Grafana instance? Doesn't Google Cloud also provide their own proprietary interface for querying the managed Prometheus?
-

**Comment by komal-rs** [comment]
@saikatdas0790 

What is the trigger for the metric collection? Let's add that
- Will do. Essentially it will be the Receiver from the OTel Collector that periodically calls the /metrics endpoint. 

Instead of spinning up a GKE cluster, let's use the offchain agent on Fly for all of our stateless processing needs? Or a separate service on Fly that will utilize the OpenTelemetry collector?
- GKE cluster is only for OTel collector and Google Managed Prometheus. Our stateless needs like gettign list of canister lies on Fly. 
- Are you saying we launch the OTel collector separately in Fly ?

How does the http_sd_config get read by Prometheus? Is this a REST API? Is there authorization involved?
- So currently in GMP, the http_sd_config responsibility lies on the OTel collector. 
- 3 parts/stages in OTel collector:
     - Receiver : This is where we add the http_sd_config in the yaml. Receiver takes the responsility to scrape metrics and get dynamic targets periodically as specified
     - Processor - this is where we can massage the data. Looking at this right now how to convert bytes we get from the canister API to Prometheus compatible data
     - Exporter - this pushes data to GMP

Are we adding authorization to the /metrics endpoint? Might be a good idea for these endpoints to be public
- We should. Will look into how this can be done in http_request. Should be straightforward mostly checking the headers.

Does Prometheus come with a frontend of its own or do we need a separate Grafana instance? Doesn't Google Cloud also provide their own proprietary interface for querying the managed Prometheus?
- It needs to be separately configured. Yes, Google Cloud provides a Prometheus UI which can be used (to be configured separately as well).

**Comment by saikatdas0790** [comment]
@komal-rs Once done exploring, let's have a final discussion on your findings and then update the doc here and the diagram to reflect what we're finally deciding to do

**Comment by komal-rs** [comment]
@saikatdas0790 sure lets discuss this tom. Noting my findings here. Ways we could solve this :

- **Approach 1**
	- Fly cron periodic app (pushes metrics to OTel collector) 
	- OTel collector as a separate process in Fly app itself that pushes to GMP
	- GMP on GKE cluster
	- similar to https://www.elias.sh/posts/opentelemetry_timeseries_metrics_and_a_bit_of_rust
	- Screenshot 2024-02-29 at 10 45 20 PM

- **Approach 2**
	- Fly cron periodic app (pushes metrics to OTel collector) 
	- OTel collector running on GKE cluster, which pushes metrics to GMP
	- GMP on GKE cluster

- **Approach 3**
	- No OTel collector
	- Fly periodic job pushing OTLP data to GMP . But this is not recommended
	- Screenshot 2024-02-29 at 10 48 50 PM

- **Approach 4** (not completely sure this will work in case of GMP, have to check)
	- No OTel collector
	- GMP on GKE 
	- Fly API to get list of targets using http_sd_config like ["https://icp-off-chain-agent.fly.dev/<canister_id_1>", "https://icp-off-chain-agent.fly.dev/<canister_id_2>", ]  . Note these will be fly APIs, not canister APIs . Calling these endpoints will further call the canister onchain and return result. Polling is taken care by GMP

- **Approach 5** 
        - Explore other solutions that take OTLP data directly and manages like Dynatrace, Signoz
	- Fly is still required in all cases

**Comment by saikatdas0790** [comment]
I have some thoughts which simplifies things further but not sure if possible. Let's discuss tomorrow.

**Review by saikatdas0790 — APPROVED** [review]

**Pull request merged**
