### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ravi-sawlani-yral**
## Changes
- added steps to check the status of deployment for canisters.

### CODE REVIEW

**Review by abhishek-tripathi-yral — APPROVED** [review]
LGTM

**Comment by abeeshake-yral** [comment]
image

How to check the status?

**Comment by abeeshake-yral** [comment]
image
3.0.12 upgrade was complete.

**Comment by ravibazz** [comment]
> image
> 
> 
> 
> How to check the status?
> 
> 

Call locally with dfx and pipe to a file

**Comment by abeeshake-yral** [comment]
sorted. feel free to merge. :)

**Pull request merged**
