### PR TITLE
added decimal handling for airdrop

### PR DESCRIPTION
**Pull request by joel-medicala-yral**
#### To check the status of the deployment

- check if the platform orchestrator performed the step to upgrade subnet canister with appropriate version: [Platform Orchestrator function](https://dashboard.internetcomputer.org/canister/74zq4-iqaaa-aaaam-ab53a-cai#get_subnet_last_upgrade_status)
- check the status of upgrade for individual canisters in subnet orchestrators and verify the version. Example for one of the subnet orchesrator: [Subnet Orchestrator function](https://dashboard.internetcomputer.org/canister/rimrc-piaaa-aaaao-aaljq-cai#get_index_details_last_upgrade_status)

To test the platform orchestrator, you can use the following command:

`dfx canister call --query 74zq4-iqaaa-aaaam-ab53a-cai get_subnet_last_upgrade_status --network=ic`
 the canister id (74zq4-iqaaa-aaaam-ab53a-cai) is taken from the canister_ids.json file

### CODE REVIEW

**Comment by rupansh-sekar-yral** [comment]
cant we do this on the frontend?

**Comment by rupansh-sekar-yral** [comment]
i'd prefer backend takes e8s from the frontend, its uniform and you dont need to handle the decimals, just update the max amount. SNS canisters have 8 decimals so the amount can be constant

**Comment by joel-medicala-yral** [comment]
> i'd prefer backend takes e8s from the frontend, its uniform and you dont need to handle the decimals, just update the max amount. SNS canisters have 8 decimals so the max amount can be constant

I dont think we can because if someone tends to call not via our frontend we won't be able to impose the 100 and 1000 token request limit

**Comment by rupansh-sekar-yral** [comment]
> > i'd prefer backend takes e8s from the frontend, its uniform and you dont need to handle the decimals, just update the max amount. SNS canisters have 8 decimals so the max amount can be constant
> 
> I dont think we can because if someone tends to call this function not via our frontend we won't be able to impose the 100 and 1000 token request limit

the max amount in the function can just be in e8s instead of looking up the decimals

**Comment by joel-medicala-yral** [comment]
Accha so you want me to hardcode the limits to 10_000_000_000 basically 100*10^8 which was previously 100* 10^decimals

**Comment by ravi-sawlani-yral** [comment]
What is this solving?

**Comment by joel-medicala-yral** [comment]
> What is this solving? 

Basically earlier we were sending 100 e8s in the request airdrop while integrating it in the frontend we decided to to not use 100e8s but 100*10^8 e8s (100 tokens) so to facilitate that a change was needed to update the limits ie multiplying all the limits by 10^8...

**Review by ravi-sawlani-yral — APPROVED** [review]

**Pull request merged**
