### PR TITLE
feat: migration PR only

### PR DESCRIPTION
**Pull request by abhishek-tripathi-yral**
the first PR for data migration aimed at backwards compatbility.

### CODE REVIEW

**Review by komal-sai-yral — COMMENTED** [review]
LGTM 

@ravibazz pls have a second look

**Comment by abeeshake-yral** [comment]
https://github.com/go-bazzinga/hot-or-not-backend-canister/blob/b46901f027191ea30e3978f163b28aba8283068f/src/canister/individual_user_template/src/util/migration.rs#L159


in related changes to tokens field from `my_token_balance` to `my_token_balance_v1` -- this module is current in use?

**Comment by komal-rs** [comment]
@abeeshake-yral I believe so. Used for the HotOrNot to Yral migration.

**Comment by abeeshake-yral** [comment]
@komal-rs @ravibazz  : rebased with main.

**Comment by abeeshake-yral** [comment]
a separate PR is not needed. Closing in favour of #354

**Pull request closed without merging**
